FluxML/Zygote.jl

src/Zygote.jl
src/lib/array.jl
test/gradcheck.jl

I've been implementing some extra adjoints in Zygote.jl for Stheno.jl and figured I should probably make a PR containing all of the ones pertaining to stuff in Base / StdLib. Let me know if there's any additional testing you want.

An assortment of adjoints

---

Project.toml
src/Zygote.jl
src/lib/array.jl
src/lib/distances.jl
test/gradcheck.jl

I screwed up and deleted the fork that #56 was associated with as a I forgot that I had this PR open. This is a fresh fork with the same changed :)

Euclidean distance rules

---

src/lib/array.jl
test/features.jl

Probably not the ideal fix but it'll avoid some errors for now.

Generalise our array zero a bit

---

docs/src/internals.md

As per #99 . Doesn't address all of the comments, but does change the formatting for read-ability.

Minor formatting change.

---

src/lib/array.jl
test/gradcheck.jl

See https://github.com/FluxML/Zygote.jl/issues/71 for context.

Add adjoint for `map`.

---

Project.toml
REQUIRE

Fixes #104. (Testing on Julia 1.0 was removed by 3d8ac06192858808e25684de52076be0a835cb37).

bump required Julia version to 1.1

---

src/lib/array.jl
test/gradcheck.jl
test/runtests.jl

Also handles `Diagonal` matrices. `gradtest` is currently producing a weird error though (that I don't think it should be / I don't understand). Will try to resolve in the morning.

Implements `cholesky` for `Diagonal` matrices

---

src/lib/lib.jl

fixes #93. Also implements the change mentioned there; gradients of mut structs are now refs-of-named-tuples.

Propagate gradients of mutable structs

---

Manifest.toml
src/lib/nnlib.jl
test/gradcheck.jl

With these changes, I can actually use Flux-on-Zygote to run some convolutional models, which is fun.

Update for NNlib overhaul

---

examples/Manifest.toml
examples/Project.toml
examples/linear_regression.jl
examples/mnist_mlp.jl
examples/profiler.jl

I think it is worthwhile to have more examples showing users what usage of Zygote can look like, as it is just so incredibly clean and beautiful.

Add more worked examples, including linear regression and an MLP MNIST

---

src/lib/buffer.jl
test/gradcheck.jl

This PR will fix the test failures in https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/71

Add a few methods to `Buffer` to make it behave like an `Array`

---

Manifest.toml
Project.toml
src/Zygote.jl
src/lib/array.jl
src/tools/fillarray.jl
test/gradcheck.jl

use FillArrays instead

---

src/lib/array.jl
test/gradcheck.jl

These don't appear to be implemented for arrays.

+, unary / binary -

---

src/lib/array.jl
test/gradcheck.jl

Functionality to ensure that broadcasting works properly with `AbstractFill`s.

FillArray broadcasting functionality

---

src/lib/array.jl
test/gradcheck.jl

Closes #52 (and removes one item from the list in #81).
I'm not sure that view takes keywords, but I just copied what Tracker has.

Adjoint for view

---

src/lib/array.jl
test/gradcheck.jl

Current implementation of multiplication uses reshape quite judiciously to ensure that the `@adjoint` for `*` returns things of the appropriate shape. This is actually only necessary in one edge-case, when we have
```julia
a::AbstractVector * x::AbstractMatrix
```
which itself only makes sense if `size(x, 1) == 1`. In this case, we need to manually ensure that the adjoint of `a` is an `AbstractVector`.
Similarly the adjoint of `permutedims` currently returns an `AbstractMatrix` when an `AbstractVector` input is provided. This fixes that in the same way.

Tidy up multiplication and permutedims

---

src/lib/array.jl

nograd any, all

---

src/lib/number.jl
test/gradcheck.jl

add adjoint for FMA

---

src/lib/array.jl
test/gradcheck.jl

Fix exp adjoint for complex matrices

---

Project.toml
src/Zygote.jl
src/lib/lib.jl

close https://github.com/FluxML/ZygoteRules.jl/issues/3
This RP requires https://github.com/FluxML/ZygoteRules.jl/pull/5 <strike>to be merged and then ZygoteRules 0.2 to be released.</strike>

Use literal_getproperty from ZygoteRules

---

src/lib/lib.jl
test/features.jl

Fix mutation + splat

---

src/lib/array.jl
test/gradcheck.jl

Add adjoints for real, conj, and imag for arrays

---

.gitlab-ci.yml
Project.toml
bors.toml
test/runtests.jl

Adds ability to work with the JuilaGPU CI setup on GitLab via Bors. Good to check compatibility with CUDA and the GPU stack. 
cc @MikeInnes

Add GPU CI

---

src/lib/array.jl
test/gradcheck.jl

hcat(scalars) & cat(…; dims)

---

src/lib/base.jl
src/lib/broadcast.jl

Ref FluxML/Flux.jl#878
This and the fix to splatting named tuples on master should work for most cases like it.
Test cases incoming
cc @MikeInnes

Add haskey adjoint

---

Manifest.toml
Project.toml

Tag v0.4.2

---

.github/workflows/CompatHelper.yml
Project.toml

This will make version handling a lot easier!

enable CompatHelper

---

Project.toml

With some of the dependency updates, tagging a quick patch release.

Bump version to v0.4.3

---

Manifest.toml
src/lib/nnlib.jl
test/gradcheck.jl

This PR depends on FluxML/NNlib.jl#148 being merged. Once that is done, `Manifest.toml` must be updated. Addresses #425.

Handle dims keyword argument in softmax adjoint

---

.gitlab-ci.yml

Fix gitlab CI

---

src/lib/broadcast.jl
test/cuda.jl

Add CuArray convert adjoint

---

src/lib/array.jl
test/gradcheck.jl

Fix converting UniformScaling to Matrix

---

src/lib/array.jl

Add @nograd for axes

---

src/compiler/interface.jl
src/tools/buffer.jl
test/interface.jl
test/runtests.jl
test/tools.jl

This is needed to expose some parameter freezing  functionality in Flux, as suggested in https://github.com/FluxML/Flux.jl/issues/1022

delete! for Params

---

src/lib/number.jl
test/gradcheck.jl

Closes #511, closes #247, and #426.

Gradient for power

---

src/lib/array.jl
test/gradcheck.jl

Gradient for filter

---

src/lib/array.jl
test/gradcheck.jl

getindex for Float32[x,y] etc.

---

src/lib/array.jl
test/gradcheck.jl

adjoint for cumsum

---

src/Zygote.jl
src/lib/range.jl

Fixes https://github.com/tpapp/TransformVariables.jl/issues/63.

Adjoints for StepRange

---

Manifest.toml
Project.toml
src/Zygote.jl
src/lib/nnlib.jl
test/gradcheck.jl

fix https://github.com/FluxML/Flux.jl/issues/1055 thanks to @dlfivefifty's suggestion in https://github.com/JuliaArrays/FillArrays.jl/issues/88
Some tests for corner cases are broken, but a fix for that will have to wait for some future PR

fix conv on cpu with fillarays

---

Manifest.toml
src/lib/array.jl
test/gradcheck.jl

fix #314 with the solution proposed by @MikeInnes here https://github.com/FluxML/Zygote.jl/issues/314#issuecomment-526135174
I updated sum and prod, but not sure if missing other reductions

fix adjoint sum(f, xs)

---

Manifest.toml
Project.toml

new release

---

Project.toml
src/lib/base.jl
test/gradcheck.jl

Resolves #548 .
Bumps patch so that we can make this available immediately.

@nograd printing

---

src/lib/array.jl

Remove extra print / println @nograds

---

Project.toml

Version bump

---

src/lib/base.jl
test/gradcheck.jl

partially fix #560 according to @mcabbott suggestion

nograd string, repr

---

Project.toml
src/lib/broadcast.jl

`CuArray`s now have their own `BroadcastStyle`.
cc @maleadt
EDIT: Fixes #567

Fix broadcast for CuArray with CuArrays 2.0

---

docs/src/adjoints.md

Avoid this possible misreading
https://discourse.julialang.org/t/understand-this-part-of-the-zygote-docs/36816

add clarifying brackets to docs on what pullback does

---

Project.toml
src/lib/broadcast.jl
test/structures.jl

reducedim_init for accum

---

.gitlab-ci.yml

Addresses https://github.com/FluxML/Zygote.jl/pull/624#issuecomment-620576528
cc @MikeInnes

Add docs to GitLab CI

---

src/lib/array.jl

Generalize https://github.com/FluxML/Zygote.jl/pull/650 to more than one argument.
Before this PR:
```
julia> @btime (x->last(map(+, fill(2x,100), fill(x,100))))'(0.1);
12.993 μs (580 allocations: 25.70 KiB)
```
After this PR:
```
julia> @btime (x->last(map(+, fill(2x,100), fill(x,100))))'(0.1);
6.746 μs (73 allocations: 12.80 KiB)
```
CC: @oxinabox

Make map with more than one argument ~2x faster

---

src/lib/base.jl
test/features.jl

Related to #664, #584
cc @MikeInnes @ChrisRackauckas

Pairs adjoint

---

.travis.yml
Project.toml
src/lib/broadcast.jl
test/cuda.jl
test/runtests.jl

also dropping julia <1.3 support
supercedes #673

move to CUDA.jl

---

Project.toml

tag a CUDA.jl and NNlib 0.7 compatible release

tag new release

---

src/lib/number.jl
test/lib/number.jl
test/runtests.jl

Fix https://github.com/FluxML/Flux.jl/issues/1244. I don't know when we lost this, maybe when moving to ChainRules?

nograd div

---

src/Zygote.jl

I guess code_grad was renamed to code_adjoint at some point

fix export

---

src/lib/array.jl
src/lib/broadcast.jl
test/gradcheck.jl

See https://github.com/FluxML/Flux.jl/issues/1209.
It would be good if we could come up with a reasonable test case. It may be tricky to do that, and if so it may make sense to merge this to avoid the issues people are seeing.

Stateful map

---

src/lib/nnlib.jl
test/gradcheck.jl

Implementing speedup of selu based on this comment: https://github.com/FluxML/Zygote.jl/pull/367#issuecomment-541844988
Utilizing vectorized ifelse based on https://github.com/FluxML/NNlib.jl/blob/master/src/activation.jl#L159.

Speed up of selu

---

Project.toml
src/lib/nnlib.jl

Bump patch version

---

src/lib/array.jl

fixes https://github.com/FluxML/Zygote.jl/issues/753

add @nograd for Base.OneTo

---

src/lib/array.jl
test/gradcheck.jl

Call the correct function for irfft(xs,d,dims)

---

src/lib/nnlib.jl
test/gradcheck.jl

Added few tests, defined adjoint for scalar selu and elu.
Fixes #578 
I hope this is right, I'm still not sure if I fully got all the tricks around adjoints.

fix for https://github.com/FluxML/Zygote.jl/issues/758

---

.gitlab-ci.yml
src/lib/base.jl
src/lib/lib.jl
test/structures.jl

Passes some of the tests for Julia 1.5 locally, but gives ~incorrect gradients for some cases.~ the right result now
Ref #768

Changes needed for Julia 1.5

---

src/compiler/show.jl
test/compiler.jl

Fixes #808 
hopefully it's done right.
Could this PR be labeled by `hacktoberfest-accepted`? 
Thanks.

Fixes #808

---

Project.toml
src/lib/array.jl
test/gradcheck.jl

This was accidentally promoting everything to Float64.

type-stable pullback for norm

---

test/chainrules.jl

Mark passing test on Julia nightly

---

src/lib/utils.jl
test/tools.jl

cc @ChrisRackauckas who wanted a utility like this

Add isderiving utility

---

docs/src/index.md

Fixed broken link to "what is differentiable programming" blog entry.

Fixed broken link

---

src/lib/array.jl
test/gradcheck.jl

This PR fixes https://github.com/FluxML/Zygote.jl/issues/932 and includes the MWE mentioned in the issue.

Fix \ for Cholesky

---

Project.toml
src/lib/array.jl

nograd `sizehint!`

---

.buildkite/pipeline.yml
src/lib/broadcast.jl
test/cuda.jl

It has been removed on CUDA master.

remove cufunc

---

src/lib/array.jl
test/gradcheck.jl

I ran into #804, and made an attempt to fix it before I noticed #846.
Unlike #846, which still runs `map`, this patch fixes #804 by propagating `Δ === nothing` through the `∇map` pullback more directly.

Handle nothing in map

---

src/lib/array.jl
test/lib/array.jl
test/runtests.jl

addresses the second part of #897

fix adjoint for sum

---

src/compiler/reverse.jl
test/compiler.jl
test/features.jl

addresses the first part of #897

fix differentiation of loopinfo exprs

---

src/compiler/interface.jl

Whitespace fixes

---

Project.toml
src/compiler/chainrules.jl
test/chainrules.jl

ProjectTo{AbstractArray}(::Tangent{Any}) fix

---

.buildkite/pipeline.yml

Changes borrowed from Flux's setup.

Update Buildkite config for 1.6 LTS and 1.7

---

Project.toml
src/lib/broadcast.jl
test/gradcheck.jl

Fixes #1178. Could use a test, perhaps.

Restrict type broadcast rule to numbers

---

docs/make.jl
docs/src/adjoints.md
docs/src/complex.md
docs/src/index.md
docs/src/profiling.md

Added a ton of doctests to index.md ( at the moment ). Will add doctests to all the markdown files if it needs to be added.
This will help to avoid documentation examples from becoming outdated, incorrect, or misleading.

Ton of doctests added

---

src/compiler/interface.jl

Fix type stability of Params.order

---

src/lib/lib.jl

Ref. https://github.com/JuliaLang/julia/commit/0deb28a4c114704c940f8eb53d3e93aca43185d3. This should address a CI failure.

Use `setglobal!` on nightly

---

Project.toml
src/lib/array.jl

These are in ChainRules.jl now
~~Edit: needs https://github.com/JuliaDiff/ChainRules.jl/pull/638 to pass tests here.~~ that is merged & tagged.

rm rules for `eachslice`, `cumsum`

---

src/lib/array.jl

ChainRules.jl should handle these.

rm rules for `Statistics.var`, `std`, `mean`

---

README.md

- Render README's logo using the logo present in this repository
- Render the logo dynamically
See https://github.com/FluxML/fluxml.github.io/pull/143, https://github.com/FluxML/Zygote.jl/pull/1306

Dynamic README logo

---

.github/workflows/CompatHelper.yml

See the failing CI jobs here - https://github.com/FluxML/Zygote.jl/actions/workflows/CompatHelper.yml

Fix and update `CompatHelper` CI

---

.gitignore
src/lib/array.jl
test/lib/array.jl

fix collect and comprehension for NamedTuple and Dict

---

src/lib/buffer.jl
test/gradcheck.jl

I checked locally and it seems this change fixes #1352. I'll add the MWE as a test, provided that existing tests still pass.

Fix issue #1352 (Buffer regression)

---

Project.toml
test/features.jl

test pycall adjoint

---

.github/workflows/Downstream.yml
.github/workflows/ci.yml
.github/workflows/clean_preview.yml

About FluxML/Flux.jl#2170
Replace deprecated actions.

update: actions node 12 => node 16

---

src/lib/array.jl

This should get nightly CI ~~green~~ closer to green again (Edit: see #1379 for the missing piece) so we're not constantly having to check for false positives. Longer term, the proper solution will be https://github.com/JuliaDiff/ChainRules.jl/issues/684.
- [N/A] Tests are added

Simple fix for `kron(::AbstractVector)` on nightly

---

docs/src/utils.md

Should fix https://github.com/FluxML/Zygote.jl/issues/1361.
- [N/A] Tests are added

Add `hessian_reverse` to docs

---

ext/ZygoteDistancesExt.jl

Fix duplicate import

---

Project.toml

Version bump to release the bugfix in #1396.

New bugfix release

---

src/lib/broadcast.jl
test/gradcheck.jl

Fix broadcasted 3-arg `*`

---

src/compiler/chainrules.jl
src/compiler/emit.jl
src/compiler/interface2.jl
src/lib/literal_getproperty.jl
test/features.jl

Fixes https://github.com/FluxML/Zygote.jl/issues/1410.

Fixes for Julia 1.10
